name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 추가된 기능들'
    label: 'develop'
  - title: '🐛 수정된 버그들'
    label: 'bug'
  - title: '🛠 인프라 변경'
    label: 'infra'
  - title: '🔄 병합됨'
    label: 'merge'
change-template: '- $TITLE #$NUMBER @$AUTHOR'
template: |
  ## 변경 사항
  ---
  $CHANGES
no-changes-template: '변경사항이 없어요'
version-resolver:
  major:
    labels:
      - 'merge'
  minor:
    labels:
      - 'develop'
  patch:
    labels:
      - 'bug'
      - 'infra'
  default: patch
