name: Opened pr notification
on:
  pull_request:
    branches: [ dev, hotfix ]
    types: [ reopened, opened ]

jobs:
  create-notification:
    name: PR opened notification to discord
    env:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
    runs-on: ubuntu-latest
    steps:
      - name : Send opened PR notification
        if: github.event.pull_request.merged != true
        uses: Ilshidur/action-discord@master  #https://github.com/marketplace/actions/actions-for-discord
        with:
          args: >
            {
              "embeds": [{
                "title": "BE 레포에 PR이 업로드 되었습니다.",
                 "color": "${{ github.event.pull_request.base.ref == 'hotfix' ? '16711680' : '255' }}",
                "description": "현재 '${{ github.event.pull_request.title }}' PR이 올라왔습니다.\n\n설명: ${{ github.event.pull_request.body }}"
              }]
            }
    



              
            

