name: Test workflows

on:
  pull_request:
    branches: [ "develop", "main", "hotfix" , "HUBOBE-*" ]
    types: [ reopened, opened, synchronize ]
    paths:
      - 'src/main/java/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Checkout secret code
        uses: actions/checkout@v3
        with:
          submodules: true
          token: ${{ secrets.ACTION_SECRETS }}

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Copy application.yml files from submodule
        run: |
          mkdir -p src/main/resources
          cp -r BE-hubo-gillajabi-resources/resources/application*.yml src/main/resources/

      - name: Copy test mocked files from submodule
        run: |
          mkdir -p src/test/resources
            cp -r BE-hubo-gillajabi-resources/test/mockedResponses/* src/test/resources/

      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: copy application.yml files from submodule
        run: |
          mkdir -p src/main/resources
          cp BE-hubo-gillajabi-resources/resources/application*.yml src/main/resources/

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Test with Gradle
        run: ./gradlew test -Dspring.profiles.active=test

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./build/reports/jacoco/test/jacocoTestReport.xml



